import { useState } from 'react'
import { useAccount } from 'wagmi'
import { useConnectModal } from '@rainbow-me/rainbowkit'
import { BRAND, FONTS, ACTIVE_CHAIN_ID, BASE_CHAIN_ID } from '../../utils/constants'
import { supabase } from '../../lib/supabase'

/**
 * Coinbase Onramp launcher — fiat → ETH/cbBTC/USDC on Base.
 *
 * Compliant with CDP Onramp security requirements (CX email 2026-04-28):
 *   1. Wallet address is NEVER in the URL — passed in the signed session
 *      token payload server-side.
 *   2. Session token is generated by `coinbase-onramp-session` Edge
 *      Function, which authenticates with our CDP API key (not exposed to
 *      the client).
 *   3. Wallet linked via SIWE is enforced server-side before the token is
 *      issued. KYC (Persona) is deferred to mint/redeem actions.
 *
 * If no wallet is connected, clicking opens RainbowKit's connect modal
 * instead of calling the Edge Function. Once connected + SIWE-linked,
 * the full Onramp flow fires.
 */

interface Props {
  presetUsd?: number
  asset?: 'ETH' | 'USDC' | 'CBBTC'
  label?: string
}

export default function OnrampButton({ presetUsd, asset = 'USDC', label }: Props) {
  const { isConnected } = useAccount()
  const { openConnectModal } = useConnectModal()
  const [pending, setPending] = useState(false)
  const [error, setError]     = useState<string | null>(null)

  async function onClick() {
    if (!isConnected) {
      openConnectModal?.()
      return
    }
    setPending(true)
    setError(null)
    try {
      const { data: { session } } = await supabase.auth.getSession()
      const accessToken = session?.access_token
      if (!accessToken) {
        setError('login_required')
        return
      }

      const res = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/coinbase-onramp-session`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${accessToken}`,
            apikey: import.meta.env.VITE_SUPABASE_ANON_KEY as string,
          },
          body: JSON.stringify({ asset, preset_usd: presetUsd }),
        },
      )
      const json = await res.json().catch(() => null) as Record<string, unknown> | null
      if (!res.ok || !json?.ok) {
        setError(typeof json?.error === 'string' ? json.error : `http_${res.status}`)
        return
      }
      const url = json.onramp_url as string | undefined
      if (!url) { setError('no_onramp_url'); return }
      window.open(url, '_blank', 'noopener,noreferrer,width=480,height=720')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'network_error')
    } finally {
      setPending(false)
    }
  }

  const chainLabel = ACTIVE_CHAIN_ID === BASE_CHAIN_ID ? 'BASE' : 'BASE SEPOLIA'
  const btnLabel = pending
    ? 'PREPARING…'
    : !isConnected
      ? `CONNECT → BUY ${asset}`
      : label ?? `BUY ${asset} WITH CARD · ${chainLabel}`

  return (
    <>
      <button
        onClick={onClick}
        disabled={pending}
        style={{ ...btnStyle, opacity: pending ? 0.6 : 1 }}
      >
        {btnLabel}
      </button>
      {error && (
        <div style={{ marginTop: 8, color: '#E47966', fontFamily: FONTS.body, fontSize: 11 }}>
          {error === 'wallet_link_required' && 'Link your wallet first via Web3 Onboarding.'}
          {error === 'geo_blocked'          && 'Your jurisdiction is not supported.'}
          {error === 'login_required'       && 'Sign in to continue.'}
          {!['wallet_link_required','geo_blocked','login_required'].includes(error) && error}
        </div>
      )}
    </>
  )
}

const btnStyle: React.CSSProperties = {
  background: BRAND.heroic,
  color: BRAND.bgDeep,
  border: 'none',
  padding: '12px 22px',
  fontFamily: FONTS.display,
  fontSize: 14,
  letterSpacing: '0.12em',
  cursor: 'pointer',
  textTransform: 'uppercase',
  fontWeight: 900,
  transition: 'opacity 0.2s',
}
