import { useState } from 'react'
import { useAccount } from 'wagmi'
import { BRAND, FONTS, BASE_CHAIN_ID } from '../../utils/constants'
import { supabase } from '../../lib/supabase'

/**
 * Coinbase Onramp launcher — fiat → ETH/cbBTC/USDC on Base.
 *
 * Compliant with CDP Onramp security requirements (CX email 2026-04-28):
 *   1. Wallet address is NEVER in the URL — passed in the signed session
 *      token payload server-side.
 *   2. Session token is generated by `coinbase-onramp-session` Edge
 *      Function, which authenticates with our CDP API key (not exposed to
 *      the client).
 *   3. KYC tier ≥ 1 + wallet linked are enforced server-side before the
 *      token is issued.
 *
 * Pricing: handled by Coinbase. Typical fee 1–2% on credit card, lower on ACH.
 * CauaCorp never touches fiat — we are NOT a Money Service Business
 * (see docs/LEGAL.md).
 */

interface Props {
  /** Optional preset purchase amount in USD. */
  presetUsd?: number
  /** Asset to buy. Defaults to USDC for easiest adoption. */
  asset?: 'ETH' | 'USDC' | 'CBBTC'
  label?: string
}

export default function OnrampButton({ presetUsd, asset = 'USDC', label }: Props) {
  const { isConnected } = useAccount()
  const [pending, setPending] = useState(false)
  const [error, setError]     = useState<string | null>(null)

  async function onClick() {
    setPending(true)
    setError(null)
    try {
      const { data: { session } } = await supabase.auth.getSession()
      const accessToken = session?.access_token
      if (!accessToken) {
        setError('login_required')
        return
      }

      const res = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/coinbase-onramp-session`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${accessToken}`,
            apikey: import.meta.env.VITE_SUPABASE_ANON_KEY as string,
          },
          body: JSON.stringify({ asset, preset_usd: presetUsd }),
        },
      )
      const json = await res.json().catch(() => null) as Record<string, unknown> | null
      if (!res.ok || !json?.ok) {
        setError(typeof json?.error === 'string' ? json.error : `http_${res.status}`)
        return
      }
      const url = json.onramp_url as string | undefined
      if (!url) {
        setError('no_onramp_url')
        return
      }
      window.open(url, '_blank', 'noopener,noreferrer,width=480,height=720')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'network_error')
    } finally {
      setPending(false)
    }
  }

  if (!isConnected) {
    return (
      <button disabled style={{ ...btnStyle, opacity: 0.4, cursor: 'not-allowed' }} title="Connect a wallet first">
        BUY {asset} WITH CARD
      </button>
    )
  }

  if (error === 'cdp_api_key_not_configured' || error === 'cdp_jwt_signing_not_implemented') {
    return (
      <button
        disabled
        style={{ ...btnStyle, opacity: 0.4, cursor: 'not-allowed' }}
        title="CDP Onramp pending approval — see docs/cdp-onramp-application-response.md"
      >
        ONRAMP CONFIG PENDING
      </button>
    )
  }

  return (
    <>
      <button onClick={onClick} disabled={pending} style={{ ...btnStyle, opacity: pending ? 0.6 : 1 }}>
        {pending
          ? 'PREPARING SESSION…'
          : label ?? `BUY ${asset} WITH CARD · ${BASE_CHAIN_ID === 8453 ? 'BASE' : 'BASE SEPOLIA'}`}
      </button>
      {error && (
        <div style={{ marginTop: 8, color: '#E47966', fontFamily: FONTS.body, fontSize: 11 }}>
          {error === 'kyc_required'        && 'Completa KYC (Tier 1+) para comprar con tarjeta.'}
          {error === 'wallet_link_required' && 'Linkea tu wallet primero.'}
          {error === 'geo_blocked'         && 'Tu jurisdicción no permite este flow.'}
          {error === 'login_required'      && 'Inicia sesión para continuar.'}
          {!['kyc_required','wallet_link_required','geo_blocked','login_required'].includes(error) && error}
        </div>
      )}
    </>
  )
}

const btnStyle: React.CSSProperties = {
  background: BRAND.heroic,
  color: BRAND.bgDeep,
  border: 'none',
  padding: '12px 22px',
  fontFamily: FONTS.display,
  fontSize: 14,
  letterSpacing: '0.12em',
  cursor: 'pointer',
  textTransform: 'uppercase',
}
